services:
  algasensors-rabbitmq:
    image: rabbitmq:3.11-management
    container_name: algasensors-rabbitmq
    restart: no
    ports:
      - "5672:5672"       # RabbitMQ main port
      - "15672:15672"     # RabbitMQ management UI port
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    volumes:
      - algasensors-rabbitmq:/var/lib/rabbitmq
volumes:
  algasensors-rabbitmq: